version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: mambaforge-latest
    rust: latest
  jobs:
    post_checkout:
      - (git --no-pager log --pretty="tformat:%s" -1 | grep -vqF "[skip-rtd]") || exit 183
      - git fetch --unshallow || true
    pre_create_environment:
      - mamba update --quiet --name base conda mamba
    create_environment:
      - mamba create --quiet --name $CONDA_DEFAULT_ENV python=3.13
      - mamba env update --quiet --name $CONDA_DEFAULT_ENV --file ci/requirements/environment.yaml
      - mamba env update --quiet --name $CONDA_DEFAULT_ENV --file ci/requirements/docs.yaml
    pre_install:
      - git update-index --assume-unchanged docs/conf.py ci/requirements/docs.yaml
    install:
      - mamba run
        -e PKG_CONFIG_PATH="$CONDA_PREFIX/lib/pkgconfig"
        --name $CONDA_DEFAULT_ENV
        maturin develop

conda:
  environment: ci/requirements/docs.yaml

sphinx:
  fail_on_warning: true
  configuration: docs/conf.py

formats: []
