channels:
  - conda-forge
dependencies:
  - rust
  - pkg-config
  - cxx-compiler
  - c-compiler
  - proj
  - sqlite
  - shapely
  - numpy
  - sparse>=0.15
  - cf-xarray
  - pytest
  - pytest-cov
  - pip
  - pip:
      - geoarrow-rust-core==0.4.0b3
